/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCollectorRouteImport } from './routes/api/collector'
import { Route as ApiDeskRouteImport } from './routes/api/desk'
import { Route as ApiMarketRouteImport } from './routes/api/market'
import { Route as ApiScanRouteImport } from './routes/api/scan'
import { Route as ApiWireRouteImport } from './routes/api/wire'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollectorRoute = ApiCollectorRouteImport.update({
  id: '/api/collector',
  path: '/api/collector',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskRoute = ApiDeskRouteImport.update({
  id: '/api/desk',
  path: '/api/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketRoute = ApiMarketRouteImport.update({
  id: '/api/market',
  path: '/api/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanRoute = ApiScanRouteImport.update({
  id: '/api/scan',
  path: '/api/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWireRoute = ApiWireRouteImport.update({
  id: '/api/wire',
  path: '/api/wire',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/collector': typeof ApiCollectorRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/market': typeof ApiMarketRoute
  '/api/scan': typeof ApiScanRoute
  '/api/wire': typeof ApiWireRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/collector': typeof ApiCollectorRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/market': typeof ApiMarketRoute
  '/api/scan': typeof ApiScanRoute
  '/api/wire': typeof ApiWireRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/collector': typeof ApiCollectorRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/market': typeof ApiMarketRoute
  '/api/scan': typeof ApiScanRoute
  '/api/wire': typeof ApiWireRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/collector'
    | '/api/desk'
    | '/api/market'
    | '/api/scan'
    | '/api/wire'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/collector'
    | '/api/desk'
    | '/api/market'
    | '/api/scan'
    | '/api/wire'
  id:
    | '__root__'
    | '/'
    | '/api/collector'
    | '/api/desk'
    | '/api/market'
    | '/api/scan'
    | '/api/wire'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCollectorRoute: typeof ApiCollectorRoute
  ApiDeskRoute: typeof ApiDeskRoute
  ApiMarketRoute: typeof ApiMarketRoute
  ApiScanRoute: typeof ApiScanRoute
  ApiWireRoute: typeof ApiWireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collector': {
      id: '/api/collector'
      path: '/api/collector'
      fullPath: '/api/collector'
      preLoaderRoute: typeof ApiCollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk': {
      id: '/api/desk'
      path: '/api/desk'
      fullPath: '/api/desk'
      preLoaderRoute: typeof ApiDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market': {
      id: '/api/market'
      path: '/api/market'
      fullPath: '/api/market'
      preLoaderRoute: typeof ApiMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan': {
      id: '/api/scan'
      path: '/api/scan'
      fullPath: '/api/scan'
      preLoaderRoute: typeof ApiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wire': {
      id: '/api/wire'
      path: '/api/wire'
      fullPath: '/api/wire'
      preLoaderRoute: typeof ApiWireRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCollectorRoute: ApiCollectorRoute,
  ApiDeskRoute: ApiDeskRoute,
  ApiMarketRoute: ApiMarketRoute,
  ApiScanRoute: ApiScanRoute,
  ApiWireRoute: ApiWireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
